export const statusNameToStatusCodeMap: Record<string, number> = {
	noerror: 0,
	formerr: 1,
	servfail: 2,
	nxdomain: 3,
	notimp: 4,
	refused: 5,
	yxdomain: 6,
	yxrrset: 7,
	nxrrset: 8,
	notauth: 9,
	notzone: 10,
	dsotypeni: 11,
	badvers: 16,
	badsig: 16,
	badkey: 17,
	badtime: 18,
	badmode: 19,
	badname: 20,
	badalg: 21,
	badtrunc: 22,
	badcookie: 23,
};
