on:
  workflow_call: {}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          sudo apt-get update
          sudo apt-get install expect
          npm ci && npm run build
      - name: lint and test
        run: |
          npm run lint
          npm run coverage
      - name: test dist
        run: |
          rm -rf node_modules
          npm ci --omit=dev
          npm run test:dist
  e2etest:
    name: Run e2e tests
    runs-on: ubicloud-standard-4
    strategy:
      matrix:
        node-version: [ 20.x ]

    env:
      NODE_ENV: test

    services:
      redis:
        image: redis/redis-stack-server:latest
        ports:
          - 16379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mariadb:
        image: mariadb:10.11.5
        ports:
          - 13306:3306
        env:
          MARIADB_DATABASE: dashboard-globalping-test
          MARIADB_USER: directus
          MARIADB_PASSWORD: password
          MARIADB_RANDOM_ROOT_PASSWORD: 1
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ubicloud/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable IPv6 for Docker containers
        run: |
          sudo cat /etc/docker/daemon.json | jq '. + { "ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64", "experimental": true, "ip6tables": true }' > daemon.json
          sudo mv daemon.json /etc/docker/
          sudo systemctl restart docker
          docker restart $(docker ps -aq)
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test E2E
        run: |
          npm run test:e2e
