name: Run tests

on:
  workflow_call: {}

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          sudo apt-get update
          sudo apt-get install expect
          npm ci && npm run build
      - name: lint and test
        run: |
          npm run lint
          npm run coverage
      - name: test dist
        run: |
          rm -rf node_modules
          npm ci --omit=dev
          npm run test:dist
